export const INITIATE_LOADING = 'INITIATE_LOADING'
export const SET_ACTIVE_LINK = 'SET_ACTIVE_LINK'
export const NAVIGATE_TO_COURSE = 'NAVIGATE_TO_COURSE'
export const ASSESSMENT_SELECTED = 'ASSESSMENT_SELECTED'